"""FastAPI application exposing the ppt-master pipeline as an HTTP API.

Swagger UI is served at /docs ; OpenAPI JSON at /openapi.json.

Endpoints:
  POST /api/presentations                     upload a source file -> create a job
  GET  /api/presentations/{job_id}            poll job status + progress
  GET  /api/presentations/{job_id}/download   download the result .zip (302 -> R2)
                                              (zip bundles the .pptx + speaker-notes .md)
  POST /api/presentations/{job_id}/cancel     stop a running/queued job
  POST /api/presentations/{job_id}/retry      resume an interrupted/failed job
"""

from __future__ import annotations

import shutil
from pathlib import Path

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.responses import FileResponse, RedirectResponse

from . import queue
from .config import settings
from .db import init_db
from .jobs import store
from .progress import compute_progress
from .registry import registry
from .schemas import (
    ACTIVE_STATUSES,
    TERMINAL_STATUSES,
    ActionResponse,
    CreateJobResponse,
    ErrorResponse,
    FormulaPolicy,
    IconStyle,
    ImageMode,
    JobStatus,
    JobStatusResponse,
)

app = FastAPI(
    title="PPT Master Service",
    version="0.2.0",
    description=(
        "Drop a source document (PDF / DOCX / Markdown / PPTX / …) and get back a "
        "natively editable .pptx, generated by the ppt-master skill via a headless "
        "Claude Code agent. Generation is asynchronous and runs through a bounded "
        "worker pool: create a job, poll status + progress, then download the result."
    ),
)


@app.on_event("startup")
async def _startup() -> None:
    settings.ensure_dirs()
    init_db()
    await queue.reconcile()
    await queue.start()


@app.on_event("shutdown")
async def _shutdown() -> None:
    await queue.shutdown()


@app.get("/healthz", tags=["meta"])
def healthz() -> dict[str, str]:
    return {"status": "ok"}


@app.post(
    "/api/presentations",
    response_model=CreateJobResponse,
    status_code=202,
    tags=["presentations"],
    responses={400: {"model": ErrorResponse}, 429: {"model": ErrorResponse}},
)
async def create_presentation(
    file: UploadFile = File(..., description="Source document: PDF / DOCX / MD / PPTX / XLSX / …"),
    canvas_format: str = Form(settings.default_format, description="①画布格式，如 ppt169 / ppt43 / xhs。"),
    page_count: str | None = Form(None, description="②页数范围，如 \"12-18\"；留空=按素材自动决定。"),
    audience: str | None = Form(None, description="③目标受众；留空=通用商务/技术读者。"),
    style_objective: str | None = Form(None, description="④风格目标，也可填风格简述（如 \"麦肯锡风\"）；留空=专业现代。"),
    color_scheme: str | None = Form(None, description="⑤配色方案；留空=策划按主题自定。"),
    icon_style: IconStyle = Form(IconStyle.line, description="⑥图标风格：line/filled/none。"),
    typography: str | None = Form(None, description="⑦字体与排版描述；留空=无衬线中英文混排。"),
    formula_policy: FormulaPolicy = Form(FormulaPolicy.mixed, description="⑦公式渲染策略：mixed/render-all/text-only。"),
    image_mode: ImageMode = Form(ImageMode.ai, description="⑧配图方式：ai(gpt-image-2)/web/placeholder/none。"),
    output_language: str | None = Form(
        None,
        description=(
            "输出语言，统一控制 PPT 正文与演讲稿语言。留空或 auto=跟随源素材语言；"
            "可填 zh / zh-tw / en / ja / ko / fr / de / es / ru，或直接写语言名（如 \"简体中文\"）。"
            "源素材可与目标语言不同（例如英文 docx 输出中文 PPT）。"
        ),
    ),
) -> CreateJobResponse:
    if not file.filename:
        raise HTTPException(status_code=400, detail="A file with a filename is required.")

    # Backpressure: reject when the pending backlog is full (0 = unbounded).
    if settings.queue_max_pending > 0 and store.count_pending() >= settings.queue_max_pending:
        raise HTTPException(
            status_code=429,
            detail=f"Queue is full ({settings.queue_max_pending} pending). Try again later.",
        )

    settings.ensure_dirs()
    safe_name = Path(file.filename).name
    dest = settings.uploads_dir / safe_name
    counter = 1
    while dest.exists():
        dest = settings.uploads_dir / f"{Path(safe_name).stem}_{counter}{Path(safe_name).suffix}"
        counter += 1
    with dest.open("wb") as out:
        shutil.copyfileobj(file.file, out)

    options = {
        "page_count": page_count,
        "audience": audience,
        "style_objective": style_objective,
        "color_scheme": color_scheme,
        "icon_style": icon_style.value,
        "typography": typography,
        "formula_policy": formula_policy.value,
        "image_mode": image_mode.value,
        "output_language": output_language,
    }
    job = store.create(
        source_filename=safe_name, canvas_format=canvas_format,
        upload_path=dest, options=options,
    )
    await queue.enqueue(job.job_id)

    return CreateJobResponse(
        job_id=job.job_id,
        status=JobStatus.PENDING,
        message="已受理，正在排队/生成。请轮询 GET /api/presentations/{job_id}。",
    )


def _status_response(job) -> JobStatusResponse:
    """Merge durable DB record with the in-memory live state. For running jobs
    the live progress (sampled from the project directory) wins; terminal jobs
    use the stored snapshot."""
    progress = job.progress
    status = job.status
    if status in ACTIVE_STATUSES and registry.is_running(job.job_id):
        handle = registry.get(job.job_id)
        project_path = handle.project_path if handle else job.project_path
        live = compute_progress(status, project_path, job.options)
        progress = max(progress, live)
    elif status == JobStatus.DONE:
        progress = 100
    download_name = job.r2_key.rsplit("/", 1)[-1] if job.r2_key else None
    return JobStatusResponse(
        job_id=job.job_id,
        status=status,
        progress=progress,
        message=job.message,
        source_filename=job.source_filename,
        canvas_format=job.canvas_format,
        pptx_filename=download_name,
        download_filename=download_name,
        download_url=job.r2_url,
        attempts=job.attempts,
        error=job.error,
        created_at=job.created_at,
        updated_at=job.updated_at,
    )


@app.get(
    "/api/presentations/{job_id}",
    response_model=JobStatusResponse,
    tags=["presentations"],
    responses={404: {"model": ErrorResponse}},
)
def get_presentation(job_id: str) -> JobStatusResponse:
    job = store.get(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail="Unknown job_id.")
    return _status_response(job)


@app.get(
    "/api/presentations/{job_id}/download",
    tags=["presentations"],
    responses={404: {"model": ErrorResponse}, 409: {"model": ErrorResponse}},
)
def download_presentation(job_id: str):
    """Download the finished job as a single .zip (deck + speaker-notes .md).
    Redirects to the packaged zip served by Cloudflare R2; the service itself
    serves no download bytes."""
    job = store.get(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail="Unknown job_id.")
    if job.status != JobStatus.DONE:
        raise HTTPException(status_code=409, detail=f"Job is not finished (status={job.status.value}).")
    if job.r2_url:
        return RedirectResponse(url=job.r2_url, status_code=302)
    if job.pptx_path and job.pptx_path.is_file():
        return FileResponse(
            path=str(job.pptx_path), filename=job.pptx_path.name,
            media_type="application/zip",
        )
    raise HTTPException(status_code=404, detail="Result file is missing.")


@app.post(
    "/api/presentations/{job_id}/cancel",
    response_model=ActionResponse,
    tags=["presentations"],
    responses={404: {"model": ErrorResponse}, 409: {"model": ErrorResponse}},
)
def cancel_presentation(job_id: str) -> ActionResponse:
    job = store.get(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail="Unknown job_id.")
    if job.status in TERMINAL_STATUSES:
        raise HTTPException(status_code=409, detail=f"Job already finished (status={job.status.value}).")
    handle = registry.get(job_id)
    if handle is not None:
        # Running here: signal cancel; the worker's finally-path marks CANCELLED.
        handle.request_cancel()
        store.update(job_id, message="收到取消请求，正在停止…")
    else:
        # Queued (or orphaned): flip to CANCELLED so a worker won't claim it.
        store.update(job_id, status=JobStatus.CANCELLED, message="任务已取消（排队中停止）。")
    return ActionResponse(job_id=job_id, status=JobStatus.CANCELLED, message="已请求取消。")


@app.post(
    "/api/presentations/{job_id}/retry",
    response_model=ActionResponse,
    tags=["presentations"],
    responses={404: {"model": ErrorResponse}, 409: {"model": ErrorResponse}},
)
async def retry_presentation(job_id: str) -> ActionResponse:
    job = store.get(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail="Unknown job_id.")
    if job.status not in (JobStatus.FAILED, JobStatus.INTERRUPTED):
        raise HTTPException(
            status_code=409,
            detail=f"Only FAILED/INTERRUPTED jobs can be retried (status={job.status.value}).",
        )
    if not job.upload_path or not Path(job.upload_path).is_file():
        # Without the source we cannot re-run; project dir (if present) may still
        # allow a resume, but a missing upload usually means it was cleaned.
        if not (job.project_path and Path(job.project_path).is_dir()):
            raise HTTPException(status_code=409, detail="Source/project no longer available for retry.")
    store.update(job_id, status=JobStatus.PENDING, error=None,
                 message="已重新入队，将从断点续跑。")
    await queue.enqueue(job_id)
    return ActionResponse(job_id=job_id, status=JobStatus.PENDING, message="已重新入队。")
