"""FastAPI application exposing the ppt-master pipeline as an HTTP API.

Swagger UI is served at /docs ; OpenAPI JSON at /openapi.json.

Endpoints:
  POST /api/presentations                     upload a source file -> create a job
  GET  /api/presentations/{job_id}            poll status + progress; returns the
                                              PPTX + notes URLs once DONE
  POST /api/presentations/{job_id}/cancel     stop a running/queued job
  POST /api/presentations/{job_id}/retry      resume an interrupted/failed job
"""

from __future__ import annotations

import hashlib
import json
import os
import tempfile
from pathlib import Path

from fastapi import FastAPI, File, Form, HTTPException, UploadFile

from . import queue
from .config import settings
from .db import init_db
from .jobs import store
from .progress import compute_progress
from .prompt_template import resolve_audience, resolve_color_scheme, resolve_style_preset
from .registry import registry
from .schemas import (
    ACTIVE_STATUSES,
    TERMINAL_STATUSES,
    ActionResponse,
    Audience,
    ColorScheme,
    CreateJobResponse,
    ErrorResponse,
    IconStyle,
    JobStatus,
    JobStatusResponse,
    OutputLanguage,
    StylePreset,
)

app = FastAPI(
    title="PPT Master Service",
    version="0.2.0",
    description=(
        "Drop a source document (PDF / DOCX / Markdown / PPTX / …) and get back a "
        "natively editable .pptx, generated by the ppt-master skill via a headless "
        "Claude Code agent. Generation is asynchronous and runs through a bounded "
        "worker pool: create a job, poll status + progress, then download the result."
    ),
)


def _configure_request_log_timestamps() -> None:
    """Prepend an ISO timestamp to uvicorn's error + access log lines.

    Uvicorn's stock formatters omit the time, so container logs read like
    ``INFO: 1.2.3.4 - "GET /x" 200`` with no way to correlate events. We reuse
    uvicorn's own formatter classes (so the access fields still render) but with
    a `%(asctime)s` prefix, and swap them onto the already-installed handlers.

    Called from startup so it runs *after* uvicorn has configured logging —
    therefore it sticks whether launched via the `uvicorn` CLI or programmatically.
    Best-effort: if uvicorn isn't the runner, this is a harmless no-op."""
    try:
        import logging

        from uvicorn.logging import AccessFormatter, DefaultFormatter
    except Exception:  # noqa: BLE001 — uvicorn not present / unexpected layout
        return

    datefmt = "%Y-%m-%d %H:%M:%S"
    default_fmt = "%(asctime)s %(levelprefix)s %(message)s"
    access_fmt = (
        '%(asctime)s %(levelprefix)s %(client_addr)s - '
        '"%(request_line)s" %(status_code)s'
    )
    for handler in logging.getLogger("uvicorn").handlers:
        handler.setFormatter(DefaultFormatter(fmt=default_fmt, datefmt=datefmt))
    for handler in logging.getLogger("uvicorn.access").handlers:
        handler.setFormatter(AccessFormatter(fmt=access_fmt, datefmt=datefmt))


@app.on_event("startup")
async def _startup() -> None:
    _configure_request_log_timestamps()
    settings.ensure_dirs()
    init_db()
    await queue.reconcile()
    await queue.start()


@app.on_event("shutdown")
async def _shutdown() -> None:
    await queue.shutdown()


@app.get("/healthz", tags=["meta"])
def healthz() -> dict[str, str]:
    return {"status": "ok"}


@app.post(
    "/api/presentations",
    response_model=CreateJobResponse,
    status_code=202,
    tags=["presentations"],
    summary="提交源文档，创建生成任务",
    description=(
        "上传源文档并按所选参数异步生成 PPTX + 演讲稿。返回 `job_id`，随后用 "
        "`GET /api/presentations/{job_id}` 轮询进度与下载链接。\n\n"
        "**幂等 / 防重放**：请求指纹 = 文件内容(SHA-256) + 全部生成参数。若已存在**相同文件且相同参数**、"
        "且处于进行中(PENDING/CONVERTING/GENERATING)或已完成(DONE)的任务，则**直接复用并返回那个 job_id**，"
        "不会重复创建——多次点击/重复提交安全。失败、取消、中断、过期的任务不在复用范围(重交即重跑)。"
        "改动任意参数或更换文件会被视为新任务。\n\n"
        "**参数说明**：画布固定 16:9、配图固定 AI、公式固定 mixed（不暴露）。常规调用只需 `file` + `style`；"
        "`color_scheme`/`audience` 为枚举(默认 auto=跟随 style/自动推断)；`page_count`/`output_language` 选填；"
        "`icon_style` 是选填的高级覆盖项，留空即用 `style` 预设默认。"
    ),
    responses={400: {"model": ErrorResponse}, 429: {"model": ErrorResponse}},
)
async def create_presentation(
    file: UploadFile = File(
        ...,
        description="源文档：PDF / DOCX / Markdown / PPTX / XLSX / TXT 等。系统会自动转换为 Markdown 再生成。",
    ),
    style: StylePreset = Form(
        StylePreset.modern,
        description=(
            "整体风格预设（决定版式语气 + 默认配色，对应代码里的 executor 风格文件）。\n"
            "• modern —— 通用现代。【默认】信息层级清晰、留白克制，适合绝大多数商务/技术汇报。\n"
            "• mckinsey —— 顶级咨询(麦肯锡/MBB)。金字塔结构、结论先行、每页一句 Takeaway、数据配对比基准。"
            "适合战略汇报、投资/尽调、高管决策材料。\n"
            "• consulting —— 商务咨询。论点清晰、图表驱动、专业稳重。适合方案、项目汇报。\n"
            "• tech —— 科技/产品。深色科技配色、强调架构与流程。适合产品发布、技术方案。\n"
            "• academic —— 学术/科研。严谨克制、重公式与图表。适合论文汇报、开题答辩、学术报告。\n"
            "• government —— 政务/党政。庄重权威、规范。适合工作汇报、政策解读、单位总结。"
        ),
    ),
    color_scheme: ColorScheme = Form(
        ColorScheme.auto,
        description=(
            "配色方案（来自代码 config.py 的 DESIGN_COLORS）。\n"
            "• auto —— 【默认】跟随所选 style 预设的配色。\n"
            "• consulting —— 深蓝主色 + 克制点缀，专业庄重。\n"
            "• general —— 蓝/绿/橙点缀、白底，明快专业。\n"
            "• tech —— 深色背景 + 青紫荧光点缀，科技未来感。\n"
            "• academic —— 暗红 + 深蓝 + 金，沉稳严谨。\n"
            "• government —— 党政红 + 深蓝 + 金，庄重正式。\n"
            "选 auto 即可；想让配色与 style 不同(如 modern 版式配 tech 深色)时再单独指定。"
        ),
    ),
    audience: Audience = Form(
        Audience.auto,
        description=(
            "目标受众（影响措辞、详略与论证侧重）。\n"
            "• auto —— 【默认】由策划根据素材内容与 style 自动推断。\n"
            "• executives —— 公司高管/决策层：结论先行，重商业影响与决策建议。\n"
            "• investors —— 投资人/资方：重市场、增长、商业模式、回报与风险。\n"
            "• technical —— 技术/工程读者：重架构、实现细节、数据与权衡。\n"
            "• academic —— 学术/科研同行：严谨论证，重方法与证据。\n"
            "• government —— 政府/评审机构：规范、权威、合规表述。\n"
            "• general —— 通用大众：通俗易懂、少术语。\n"
            "• students —— 学生/教学：循序渐进、重讲解与示例。\n"
            "• internal —— 公司内部团队：务实，聚焦执行与协作。"
        ),
    ),
    page_count: int | None = Form(
        None,
        ge=1,
        le=60,
        description=(
            "目标页数(数字)。留空=由系统按素材体量自动决定(建议 12–18 页)。"
            "填具体数字则按该页数生成；常用区间：精简 8–12、标准 12–18、详尽 18–28。"
        ),
    ),
    output_language: OutputLanguage = Form(
        OutputLanguage.auto,
        description=(
            "输出语言，统一控制 PPT 正文与演讲稿的语言(可与源素材语言不同)。\n"
            "• auto —— 【默认】跟随源素材语言(英文素材→英文成稿)。\n"
            "• zh —— 简体中文。  • zh-tw —— 繁体中文。  • en —— English。\n"
            "• ja —— 日本語。  • ko —— 한국어。  • fr —— Français。\n"
            "• de —— Deutsch。  • es —— Español。  • ru —— Русский。\n"
            "典型用法：英文 docx 想输出中文汇报 → 选 zh。"
        ),
    ),
    icon_style: IconStyle | None = Form(
        None,
        description=(
            "【高级覆盖·选填】图标风格。留空=采用 style 预设默认(多为 line)。\n"
            "• line —— 线性图标，轻盈现代。\n"
            "• filled —— 实心图标，醒目厚重(政务/强调场景)。\n"
            "• none —— 不使用图标。"
        ),
    ),
) -> CreateJobResponse:
    if not file.filename:
        raise HTTPException(status_code=400, detail="A file with a filename is required.")

    # Backpressure: reject when the pending backlog is full (0 = unbounded).
    if settings.queue_max_pending > 0 and store.count_pending() >= settings.queue_max_pending:
        raise HTTPException(
            status_code=429,
            detail=f"Queue is full ({settings.queue_max_pending} pending). Try again later.",
        )

    settings.ensure_dirs()
    safe_name = Path(file.filename).name

    # Stream the upload to a temp file while hashing its bytes, so we can
    # de-duplicate before committing it to the uploads dir.
    digest = hashlib.sha256()
    fd, tmp_path = tempfile.mkstemp(dir=str(settings.uploads_dir), suffix=".part")
    with os.fdopen(fd, "wb") as out:
        while True:
            chunk = file.file.read(1 << 20)
            if not chunk:
                break
            digest.update(chunk)
            out.write(chunk)
    file_hash = digest.hexdigest()

    # Resolve the style preset into the underlying eight-confirmation fields.
    preset = resolve_style_preset(style.value)
    lang = None if output_language == OutputLanguage.auto else output_language.value
    # Fixed (not user-selectable): canvas 16:9, AI illustrations, mixed formulas.
    fixed_canvas = "ppt169"
    fixed_image_mode = "ai"
    fixed_formula_policy = "mixed"
    # color_scheme / audience: enum -> concrete brief ('auto' keeps preset/infer).
    eff_color_scheme = resolve_color_scheme(color_scheme.value, preset)
    eff_audience = resolve_audience(audience.value)
    eff_typography = preset["typography"]
    eff_icon_style = icon_style.value if icon_style is not None else preset["icon_style"]

    # Request fingerprint = file content + every parameter that affects output.
    fp_payload = json.dumps(
        {
            "file": file_hash,
            "canvas_format": fixed_canvas,
            "style": style.value,
            "page_count": page_count,
            "image_mode": fixed_image_mode,
            "formula_policy": fixed_formula_policy,
            "output_language": lang or "auto",
            "color_scheme": color_scheme.value,
            "audience": audience.value,
            "typography": eff_typography,
            "icon_style": eff_icon_style,
        },
        sort_keys=True,
        ensure_ascii=False,
    )
    fingerprint = hashlib.sha256(fp_payload.encode("utf-8")).hexdigest()

    # Idempotency / replay protection: reuse an identical in-flight or finished job.
    existing = store.find_reusable(fingerprint)
    if existing is not None:
        os.unlink(tmp_path)  # discard the duplicate upload
        return CreateJobResponse(
            job_id=existing.job_id,
            status=existing.status,
            message=(
                f"检测到相同文件与参数的任务，已复用现有任务 {existing.job_id}"
                f"（当前状态 {existing.status.value}）。如需强制重新生成，请改动参数或文件。"
            ),
        )

    # New request: move the temp upload to its final name (avoid collisions).
    dest = settings.uploads_dir / safe_name
    counter = 1
    while dest.exists():
        dest = settings.uploads_dir / f"{Path(safe_name).stem}_{counter}{Path(safe_name).suffix}"
        counter += 1
    os.replace(tmp_path, dest)

    options = {
        "page_count": str(page_count) if page_count else None,
        "audience": eff_audience,  # None = Strategist infers from content + style
        "style_objective": preset["style_objective"],
        "color_scheme": eff_color_scheme,
        "icon_style": eff_icon_style,
        "typography": eff_typography,
        "formula_policy": fixed_formula_policy,
        "image_mode": fixed_image_mode,
        "output_language": lang,
        "style_preset": style.value,
    }
    job = store.create(
        source_filename=safe_name, canvas_format=fixed_canvas,
        upload_path=dest, options=options, fingerprint=fingerprint,
    )
    await queue.enqueue(job.job_id)

    return CreateJobResponse(
        job_id=job.job_id,
        status=JobStatus.PENDING,
        message="已受理，正在排队/生成。请轮询 GET /api/presentations/{job_id}。",
    )


def _status_response(job) -> JobStatusResponse:
    """Merge durable DB record with the in-memory live state. For running jobs
    the live progress (sampled from the project directory) wins; terminal jobs
    use the stored snapshot."""
    progress = job.progress
    status = job.status
    if status in ACTIVE_STATUSES and registry.is_running(job.job_id):
        handle = registry.get(job.job_id)
        project_path = handle.project_path if handle else job.project_path
        live = compute_progress(status, project_path, job.options)
        progress = max(progress, live)
    elif status == JobStatus.DONE:
        progress = 100
    download_name = job.r2_key.rsplit("/", 1)[-1] if job.r2_key else None
    return JobStatusResponse(
        job_id=job.job_id,
        status=status,
        progress=progress,
        message=job.message,
        source_filename=job.source_filename,
        canvas_format=job.canvas_format,
        pptx_filename=download_name,
        download_filename=download_name,
        download_url=job.r2_url,
        notes_url=job.notes_url,
        attempts=job.attempts,
        error=job.error,
        created_at=job.created_at,
        updated_at=job.updated_at,
    )


@app.get(
    "/api/presentations/{job_id}",
    response_model=JobStatusResponse,
    tags=["presentations"],
    summary="查询任务状态 / 进度 / 下载链接",
    description=(
        "轮询单个任务的状态。\n\n"
        "**处理中**(PENDING / CONVERTING / GENERATING)：返回 `progress`(0–100) 用于显示进度条；"
        "`download_url` / `notes_url` 为 null。\n\n"
        "**已完成**(DONE)：`progress`=100，并额外返回两个 Cloudflare 公开 URL（两个文件**分别上传**、"
        "非压缩包，URL 已拼接好可直接访问）：\n"
        "- `download_url` —— PPTX 文件，可直接下载或嵌入。\n"
        "- `notes_url` —— 演讲稿 .md 文件（无备注时为 null）。\n\n"
        "**失败/中断**(FAILED / INTERRUPTED)：`error` 给出原因；INTERRUPTED 可调用 `/retry` 续跑。\n\n"
        "建议轮询间隔 2–5 秒。"
    ),
    responses={404: {"model": ErrorResponse}},
)
def get_presentation(job_id: str) -> JobStatusResponse:
    job = store.get(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail="Unknown job_id.")
    return _status_response(job)


@app.post(
    "/api/presentations/{job_id}/cancel",
    response_model=ActionResponse,
    tags=["presentations"],
    summary="取消一个排队中或正在生成的任务",
    description=(
        "停止任务。正在生成的会终止智能体进程并清理本地产物 + 已写入的 R2 对象，置为 CANCELLED；"
        "排队中的直接置 CANCELLED 不再被领取。已处于终态(DONE/FAILED/CANCELLED/INTERRUPTED/EXPIRED)返回 409。"
    ),
    responses={404: {"model": ErrorResponse}, 409: {"model": ErrorResponse}},
)
def cancel_presentation(job_id: str) -> ActionResponse:
    job = store.get(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail="Unknown job_id.")
    if job.status in TERMINAL_STATUSES:
        raise HTTPException(status_code=409, detail=f"Job already finished (status={job.status.value}).")
    handle = registry.get(job_id)
    if handle is not None:
        # Running here: signal cancel; the worker's finally-path marks CANCELLED.
        handle.request_cancel()
        store.update(job_id, message="收到取消请求，正在停止…")
    else:
        # Queued (or orphaned): flip to CANCELLED so a worker won't claim it.
        store.update(job_id, status=JobStatus.CANCELLED, message="任务已取消（排队中停止）。")
    return ActionResponse(job_id=job_id, status=JobStatus.CANCELLED, message="已请求取消。")


@app.post(
    "/api/presentations/{job_id}/retry",
    response_model=ActionResponse,
    tags=["presentations"],
    summary="重试 / 断点续跑一个失败或中断的任务",
    description=(
        "对 **FAILED 或 INTERRUPTED** 的任务重新入队，从**断点续跑**——不是整段重来。\n\n"
        "原理：之前运行落盘的中间产物(策划大纲、已生成的页 SVG、配图、备注等)都保留着；"
        "续跑时智能体会检查这些产物，**只补做未完成的步骤**，已完成的不重做，从而省下最贵的逐页生成。\n\n"
        "前提：源文件或项目目录仍存在(只有 DONE 成功后才会清理它们，所以失败/中断的任务通常可重试)。\n\n"
        "适用场景：\n"
        "- 中转站/模型调用抖动导致失败(系统已自动重试 2 次仍失败 → INTERRUPTED)；\n"
        "- 服务重启导致进行中的任务被标记为 INTERRUPTED；\n"
        "- R2 上传失败留下的本地产物。\n\n"
        "调用后任务回到 PENDING 并由工作池择机执行；用 `GET /api/presentations/{job_id}` 继续轮询进度。\n\n"
        "状态非 FAILED/INTERRUPTED(如仍在处理或已 DONE)返回 409；源/项目均已不存在返回 409。"
    ),
    responses={404: {"model": ErrorResponse}, 409: {"model": ErrorResponse}},
)
async def retry_presentation(job_id: str) -> ActionResponse:
    job = store.get(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail="Unknown job_id.")
    if job.status not in (JobStatus.FAILED, JobStatus.INTERRUPTED):
        raise HTTPException(
            status_code=409,
            detail=f"Only FAILED/INTERRUPTED jobs can be retried (status={job.status.value}).",
        )
    if not job.upload_path or not Path(job.upload_path).is_file():
        # Without the source we cannot re-run; project dir (if present) may still
        # allow a resume, but a missing upload usually means it was cleaned.
        if not (job.project_path and Path(job.project_path).is_dir()):
            raise HTTPException(status_code=409, detail="Source/project no longer available for retry.")
    store.update(job_id, status=JobStatus.PENDING, error=None,
                 message="已重新入队，将从断点续跑。")
    await queue.enqueue(job_id)
    return ActionResponse(job_id=job_id, status=JobStatus.PENDING, message="已重新入队。")
